# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udp_packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import kwek_pb2 as kwek__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='udp_packet.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10udp_packet.proto\x1a\nkwek.proto\"\xd1\x02\n\tUdpPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x1a\x46\n\nCreateKwek\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x13\n\x04kwek\x18\x02 \x01(\x0b\x32\x05.Kwek\x1a\x46\n\tGameState\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x14\n\x05kweks\x18\x02 \x03(\x0b\x32\x05.Kwek\x1aX\n\x06Motion\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x13\n\x04kwek\x18\x02 \x02(\x0b\x32\x05.Kwek\x12\t\n\x01x\x18\x03 \x02(\x02\x12\t\n\x01y\x18\x04 \x02(\x02\"5\n\nPacketType\x12\x0f\n\x0b\x43REATE_KWEK\x10\x00\x12\n\n\x06GSTATE\x10\x01\x12\n\n\x06MOTION\x10\x02')
  ,
  dependencies=[kwek__pb2.DESCRIPTOR,])



_UDPPACKET_PACKETTYPE = _descriptor.EnumDescriptor(
  name='PacketType',
  full_name='UdpPacket.PacketType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_KWEK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GSTATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOTION', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=317,
  serialized_end=370,
)
_sym_db.RegisterEnumDescriptor(_UDPPACKET_PACKETTYPE)


_UDPPACKET_CREATEKWEK = _descriptor.Descriptor(
  name='CreateKwek',
  full_name='UdpPacket.CreateKwek',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.CreateKwek.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kwek', full_name='UdpPacket.CreateKwek.kwek', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=153,
)

_UDPPACKET_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='UdpPacket.GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.GameState.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kweks', full_name='UdpPacket.GameState.kweks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=225,
)

_UDPPACKET_MOTION = _descriptor.Descriptor(
  name='Motion',
  full_name='UdpPacket.Motion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.Motion.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kwek', full_name='UdpPacket.Motion.kwek', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='UdpPacket.Motion.x', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='UdpPacket.Motion.y', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=315,
)

_UDPPACKET = _descriptor.Descriptor(
  name='UdpPacket',
  full_name='UdpPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UDPPACKET_CREATEKWEK, _UDPPACKET_GAMESTATE, _UDPPACKET_MOTION, ],
  enum_types=[
    _UDPPACKET_PACKETTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=370,
)

_UDPPACKET_CREATEKWEK.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_CREATEKWEK.fields_by_name['kwek'].message_type = kwek__pb2._KWEK
_UDPPACKET_CREATEKWEK.containing_type = _UDPPACKET
_UDPPACKET_GAMESTATE.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_GAMESTATE.fields_by_name['kweks'].message_type = kwek__pb2._KWEK
_UDPPACKET_GAMESTATE.containing_type = _UDPPACKET
_UDPPACKET_MOTION.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_MOTION.fields_by_name['kwek'].message_type = kwek__pb2._KWEK
_UDPPACKET_MOTION.containing_type = _UDPPACKET
_UDPPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_PACKETTYPE.containing_type = _UDPPACKET
DESCRIPTOR.message_types_by_name['UdpPacket'] = _UDPPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UdpPacket = _reflection.GeneratedProtocolMessageType('UdpPacket', (_message.Message,), dict(

  CreateKwek = _reflection.GeneratedProtocolMessageType('CreateKwek', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_CREATEKWEK,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.CreateKwek)
    ))
  ,

  GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_GAMESTATE,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.GameState)
    ))
  ,

  Motion = _reflection.GeneratedProtocolMessageType('Motion', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_MOTION,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.Motion)
    ))
  ,
  DESCRIPTOR = _UDPPACKET,
  __module__ = 'udp_packet_pb2'
  # @@protoc_insertion_point(class_scope:UdpPacket)
  ))
_sym_db.RegisterMessage(UdpPacket)
_sym_db.RegisterMessage(UdpPacket.CreateKwek)
_sym_db.RegisterMessage(UdpPacket.GameState)
_sym_db.RegisterMessage(UdpPacket.Motion)


# @@protoc_insertion_point(module_scope)
